namespace _8_CustomerSupportFWorkflow.Models;

//{
//  "id": <Auto-generated ticket id>,
//  "from": "<Customer's email address, fictitious if not provided>",
//  "message": "<The original email message>",
//  "summary": "<One sentence summary of the email>",
//  "intent": "<Complaint|Request|Feedback|Other>",
//  "urgency": "<Low|Medium|High>",
//}
internal class Ticket
{
    public int Id { get; set; }
    public string From { get; set; } = string.Empty;
    public string Message { get; set; } = string.Empty;
    public string Summary { get; set; } = string.Empty;
    public string Intent { get; set; } = string.Empty;
    public string Urgency { get; set; } = string.Empty;
    public DateTime CreatedAt { get; set; }
}
